#!/bin/bash

# A simple script to notify of new arch pacman updates via KDE kdialogs.
# By: Wes Brewer [nd3, Zer0] - Aug 28, 2006
# Last updated on Oct 13, 2006 (friday the 13th.. ooh spooky)

# Import user settings
. /etc/karchnotify.conf

# Notify the user that we are checking for updates. (visual that the script is running)
kdialog --title "KArchNotify" --passivepopup "Checking for updates.." 10 &

# Grab latest package list from repos (note: you must be root)
# You could add your user to the wheel group and setup your sudo properly
pacman --noconfirm -Sy

# Get list of updates and grab the package names only (remove ftp path, pkg.tar.gz, blank lines)
if [ "$showver" = "1" ]; then # Show version?
  pacman --noconfirm -Sup | sed -e 's/^.*i686\///' -e 's/.pkg.tar.gz//' -e'/^ *$/d' > /tmp/paclist
else
  pacman --noconfirm -Sup | sed -e 's/^.*i686\///' -e 's/-[0-9].*//' -e'/^ *$/d' > /tmp/paclist
fi

if [ "$horz" = "1" ]; then  # Horizontal display?
  paclist=`cat /tmp/paclist | sed 's/^/  /' | tr "\n" "\t"`
else
  paclist=`cat /tmp/paclist`
fi

# Get number of updates available
numpacs=`wc -l /tmp/paclist | cut -d" " -f1`

if [ "$numpacs" \> "0" ]; then    # Only display if there are updates available
  # Oldschool display (passive popup list) or new display? 
  if [ "$oldskwl" = "1" ]; then
    # Output to KDE passive popup
    kdialog --title "$att: $numpacs new updates are available..." --passivepopup "$paclist" $timeout
  else
    # Output to KDE list updates prompt
    kdialog --title "KArchNotify" --yesno "$att: $numpacs new updates are available...\n List available updates?"
    if [ $? = 0 ]; then #check if yes was selected
      kdialog --title "KArchNotify: Updates List" --textbox /tmp/paclist 400 300  #output to KDE textbox with list of updates
    fi
  fi
fi

